// <auto-generated />
using System;
using MasterAdvantage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterAdvantage.Migrations
{
    [DbContext(typeof(MasterAdvantageContext))]
    [Migration("20240829155230_AddTrades")]
    partial class AddTrades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MasterAdvantage.Shared.Components.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Components.EncounterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionsUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConditionsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CreatureId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStamina")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Initiative")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId");

                    b.HasIndex("EncounterId");

                    b.ToTable("EncounterItems");
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Entities.Creature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSrc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MDR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStamina")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PDR")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Creatures");

                    b.HasDiscriminator().HasValue("Creature");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Attribute")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Entities.Character", b =>
                {
                    b.HasBaseType("MasterAdvantage.Shared.Entities.Creature");

                    b.Property<int>("AcrobaticsMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AgilitySave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArcanaMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AthleticsMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwarenessMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CharismaSave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomKnowledge1Mastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomKnowledge1Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomKnowledge2Mastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomKnowledge2Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HistoryMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InfluenceMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InsightMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IntelligenceSave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntimidationMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvestigationMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicineMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Might")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MightSave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NatureMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OccultismMastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReligionMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StealthMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurvivalMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrickeryMastery")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Character");
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Components.EncounterItem", b =>
                {
                    b.HasOne("MasterAdvantage.Shared.Entities.Creature", "Creature")
                        .WithMany()
                        .HasForeignKey("CreatureId");

                    b.HasOne("MasterAdvantage.Shared.Components.Encounter", "Encounter")
                        .WithMany("Items")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creature");

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Entities.Trade", b =>
                {
                    b.HasOne("MasterAdvantage.Shared.Entities.Character", "Character")
                        .WithMany("Trades")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Components.Encounter", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Entities.Character", b =>
                {
                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
