// <auto-generated />
using System;
using MasterAdvantage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterAdvantage.Migrations
{
    [DbContext(typeof(MasterAdvantageContext))]
    [Migration("20240827213332_MoveConditions")]
    partial class MoveConditions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MasterAdvantage.Shared.Components.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Encounters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("748ed191-0a60-478c-82fa-8c96137c1db7"),
                            Name = "First Encounter"
                        });
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Components.EncounterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Action1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Action2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Action3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Action4")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConditionsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CreatureId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStamina")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Initiative")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId");

                    b.HasIndex("EncounterId");

                    b.ToTable("EncounterItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4f7238c8-2b0e-4b6e-abee-f8d5aa6ee777"),
                            Action1 = false,
                            Action2 = false,
                            Action3 = false,
                            Action4 = false,
                            Conditions = "[]",
                            ConditionsOpen = false,
                            CreatureId = new Guid("15abf7c3-2780-4cec-b672-1af0bc17b486"),
                            CurrentHP = 0,
                            CurrentMana = 0,
                            CurrentStamina = 0,
                            EncounterId = new Guid("748ed191-0a60-478c-82fa-8c96137c1db7"),
                            Hidden = false,
                            Initiative = 0
                        },
                        new
                        {
                            Id = new Guid("93bae85a-37c4-406e-b6e9-6970e1166e41"),
                            Action1 = false,
                            Action2 = false,
                            Action3 = false,
                            Action4 = false,
                            Conditions = "[]",
                            ConditionsOpen = false,
                            CreatureId = new Guid("e0f124e0-7ef5-4b11-a09a-15c2b8f0605f"),
                            CurrentHP = 0,
                            CurrentMana = 0,
                            CurrentStamina = 0,
                            EncounterId = new Guid("748ed191-0a60-478c-82fa-8c96137c1db7"),
                            Hidden = false,
                            Initiative = 0
                        },
                        new
                        {
                            Id = new Guid("1d11fba5-e645-4427-a620-8778972794be"),
                            Action1 = false,
                            Action2 = false,
                            Action3 = false,
                            Action4 = false,
                            Conditions = "[]",
                            ConditionsOpen = false,
                            CreatureId = new Guid("bb9eabbf-5d14-4646-8f51-c4019da03600"),
                            CurrentHP = 0,
                            CurrentMana = 0,
                            CurrentStamina = 0,
                            EncounterId = new Guid("748ed191-0a60-478c-82fa-8c96137c1db7"),
                            Hidden = false,
                            Initiative = 0
                        },
                        new
                        {
                            Id = new Guid("0ecb2f3b-4624-4d9d-8497-28f24a6fdf33"),
                            Action1 = false,
                            Action2 = false,
                            Action3 = false,
                            Action4 = false,
                            Conditions = "[]",
                            ConditionsOpen = false,
                            CreatureId = new Guid("72b54097-0782-465a-a0d4-d338d721420d"),
                            CurrentHP = 0,
                            CurrentMana = 0,
                            CurrentStamina = 0,
                            EncounterId = new Guid("748ed191-0a60-478c-82fa-8c96137c1db7"),
                            Hidden = false,
                            Initiative = 0
                        });
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Entities.Creature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("MD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MDR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStamina")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PDR")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Creatures");

                    b.HasDiscriminator().HasValue("Creature");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Entities.Character", b =>
                {
                    b.HasBaseType("MasterAdvantage.Shared.Entities.Creature");

                    b.Property<int>("AcrobaticsMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AgilitySave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArcanaMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AthleticsMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwarenessMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CharismaSave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomKnowledge1Mastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomKnowledge1Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomKnowledge2Mastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomKnowledge2Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HistoryMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InfluenceMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InsightMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IntelligenceSave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntimidationMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvestigationMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicineMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Might")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MightSave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NatureMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OccultismMastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReligionMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StealthMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurvivalMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrickeryMastery")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Character");

                    b.HasData(
                        new
                        {
                            Id = new Guid("15abf7c3-2780-4cec-b672-1af0bc17b486"),
                            ActionPoints = 4,
                            MD = 0,
                            MDR = 0,
                            MaxHP = 0,
                            MaxMana = 0,
                            MaxStamina = 0,
                            Name = "The Bear Dru",
                            PD = 0,
                            PDR = 0,
                            AcrobaticsMastery = 0,
                            Agility = 0,
                            AgilitySave = false,
                            AnimalMastery = 0,
                            ArcanaMastery = 0,
                            AthleticsMastery = 0,
                            AwarenessMastery = 0,
                            Charisma = 0,
                            CharismaSave = false,
                            CustomKnowledge1Mastery = 0,
                            CustomKnowledge1Name = "",
                            CustomKnowledge2Mastery = 0,
                            CustomKnowledge2Name = "",
                            HistoryMastery = 0,
                            InfluenceMastery = 0,
                            InsightMastery = 0,
                            Intelligence = 0,
                            IntelligenceSave = false,
                            IntimidationMastery = 0,
                            InvestigationMastery = 0,
                            Level = 1,
                            MedicineMastery = 0,
                            Might = 0,
                            MightSave = false,
                            NatureMastery = 0,
                            OccultismMastery = 0,
                            PlayerName = "Nate",
                            ReligionMastery = 0,
                            StealthMastery = 0,
                            SurvivalMastery = 0,
                            TrickeryMastery = 0
                        },
                        new
                        {
                            Id = new Guid("e0f124e0-7ef5-4b11-a09a-15c2b8f0605f"),
                            ActionPoints = 4,
                            MD = 0,
                            MDR = 0,
                            MaxHP = 0,
                            MaxMana = 0,
                            MaxStamina = 0,
                            Name = "Ishraq",
                            PD = 0,
                            PDR = 0,
                            AcrobaticsMastery = 0,
                            Agility = 0,
                            AgilitySave = false,
                            AnimalMastery = 0,
                            ArcanaMastery = 0,
                            AthleticsMastery = 0,
                            AwarenessMastery = 0,
                            Charisma = 0,
                            CharismaSave = false,
                            CustomKnowledge1Mastery = 0,
                            CustomKnowledge1Name = "",
                            CustomKnowledge2Mastery = 0,
                            CustomKnowledge2Name = "",
                            HistoryMastery = 0,
                            InfluenceMastery = 0,
                            InsightMastery = 0,
                            Intelligence = 0,
                            IntelligenceSave = false,
                            IntimidationMastery = 0,
                            InvestigationMastery = 0,
                            Level = 1,
                            MedicineMastery = 0,
                            Might = 0,
                            MightSave = false,
                            NatureMastery = 0,
                            OccultismMastery = 0,
                            PlayerName = "James",
                            ReligionMastery = 0,
                            StealthMastery = 0,
                            SurvivalMastery = 0,
                            TrickeryMastery = 0
                        },
                        new
                        {
                            Id = new Guid("bb9eabbf-5d14-4646-8f51-c4019da03600"),
                            ActionPoints = 4,
                            MD = 0,
                            MDR = 0,
                            MaxHP = 0,
                            MaxMana = 0,
                            MaxStamina = 0,
                            Name = "Kerf",
                            PD = 0,
                            PDR = 0,
                            AcrobaticsMastery = 0,
                            Agility = 0,
                            AgilitySave = false,
                            AnimalMastery = 0,
                            ArcanaMastery = 0,
                            AthleticsMastery = 0,
                            AwarenessMastery = 0,
                            Charisma = 0,
                            CharismaSave = false,
                            CustomKnowledge1Mastery = 0,
                            CustomKnowledge1Name = "",
                            CustomKnowledge2Mastery = 0,
                            CustomKnowledge2Name = "",
                            HistoryMastery = 0,
                            InfluenceMastery = 0,
                            InsightMastery = 0,
                            Intelligence = 0,
                            IntelligenceSave = false,
                            IntimidationMastery = 0,
                            InvestigationMastery = 0,
                            Level = 1,
                            MedicineMastery = 0,
                            Might = 0,
                            MightSave = false,
                            NatureMastery = 0,
                            OccultismMastery = 0,
                            PlayerName = "Alex",
                            ReligionMastery = 0,
                            StealthMastery = 0,
                            SurvivalMastery = 0,
                            TrickeryMastery = 0
                        },
                        new
                        {
                            Id = new Guid("72b54097-0782-465a-a0d4-d338d721420d"),
                            ActionPoints = 4,
                            MD = 0,
                            MDR = 0,
                            MaxHP = 0,
                            MaxMana = 0,
                            MaxStamina = 0,
                            Name = "Marf",
                            PD = 0,
                            PDR = 0,
                            AcrobaticsMastery = 0,
                            Agility = 0,
                            AgilitySave = false,
                            AnimalMastery = 0,
                            ArcanaMastery = 0,
                            AthleticsMastery = 0,
                            AwarenessMastery = 0,
                            Charisma = 0,
                            CharismaSave = false,
                            CustomKnowledge1Mastery = 0,
                            CustomKnowledge1Name = "",
                            CustomKnowledge2Mastery = 0,
                            CustomKnowledge2Name = "",
                            HistoryMastery = 0,
                            InfluenceMastery = 0,
                            InsightMastery = 0,
                            Intelligence = 0,
                            IntelligenceSave = false,
                            IntimidationMastery = 0,
                            InvestigationMastery = 0,
                            Level = 1,
                            MedicineMastery = 0,
                            Might = 0,
                            MightSave = false,
                            NatureMastery = 0,
                            OccultismMastery = 0,
                            PlayerName = "Spence",
                            ReligionMastery = 0,
                            StealthMastery = 0,
                            SurvivalMastery = 0,
                            TrickeryMastery = 0
                        });
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Components.EncounterItem", b =>
                {
                    b.HasOne("MasterAdvantage.Shared.Entities.Creature", "Creature")
                        .WithMany()
                        .HasForeignKey("CreatureId");

                    b.HasOne("MasterAdvantage.Shared.Components.Encounter", "Encounter")
                        .WithMany("Items")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creature");

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Components.Encounter", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
