// <auto-generated />
using System;
using MasterAdvantage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterAdvantage.Migrations
{
    [DbContext(typeof(MasterAdvantageContext))]
    [Migration("20240827213146_AddConditions")]
    partial class AddConditions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MasterAdvantage.Shared.Components.Encounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Encounters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6c67300-d0a4-443a-9de6-865846fbd4ef"),
                            Name = "First Encounter"
                        });
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Components.EncounterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Action1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Action2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Action3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Action4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConditionsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CreatureId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentHP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStamina")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("EncounterId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Initiative")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId");

                    b.HasIndex("EncounterId");

                    b.ToTable("EncounterItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2d60cc0-cb78-4d02-a79a-947d010bce3e"),
                            Action1 = false,
                            Action2 = false,
                            Action3 = false,
                            Action4 = false,
                            ConditionsOpen = false,
                            CreatureId = new Guid("66432fcd-8910-4364-9579-6e9b26417270"),
                            CurrentHP = 0,
                            CurrentMana = 0,
                            CurrentStamina = 0,
                            EncounterId = new Guid("c6c67300-d0a4-443a-9de6-865846fbd4ef"),
                            Hidden = false,
                            Initiative = 0
                        },
                        new
                        {
                            Id = new Guid("1585efc7-0693-484a-b966-9893ba142c91"),
                            Action1 = false,
                            Action2 = false,
                            Action3 = false,
                            Action4 = false,
                            ConditionsOpen = false,
                            CreatureId = new Guid("0b655dc7-1f5f-4afe-b384-d8b4298b704e"),
                            CurrentHP = 0,
                            CurrentMana = 0,
                            CurrentStamina = 0,
                            EncounterId = new Guid("c6c67300-d0a4-443a-9de6-865846fbd4ef"),
                            Hidden = false,
                            Initiative = 0
                        },
                        new
                        {
                            Id = new Guid("ccba4ba0-fe89-4fed-be68-eb9919b72b16"),
                            Action1 = false,
                            Action2 = false,
                            Action3 = false,
                            Action4 = false,
                            ConditionsOpen = false,
                            CreatureId = new Guid("09fb353d-e506-44ee-a7e4-4cd3a09a13bc"),
                            CurrentHP = 0,
                            CurrentMana = 0,
                            CurrentStamina = 0,
                            EncounterId = new Guid("c6c67300-d0a4-443a-9de6-865846fbd4ef"),
                            Hidden = false,
                            Initiative = 0
                        },
                        new
                        {
                            Id = new Guid("01215a42-20d6-4640-a889-2838c5a15926"),
                            Action1 = false,
                            Action2 = false,
                            Action3 = false,
                            Action4 = false,
                            ConditionsOpen = false,
                            CreatureId = new Guid("8333de00-7bf7-4394-850d-d42c794bdd2d"),
                            CurrentHP = 0,
                            CurrentMana = 0,
                            CurrentStamina = 0,
                            EncounterId = new Guid("c6c67300-d0a4-443a-9de6-865846fbd4ef"),
                            Hidden = false,
                            Initiative = 0
                        });
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Entities.Creature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<int>("MD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MDR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxHP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxMana")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStamina")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PDR")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Creatures");

                    b.HasDiscriminator().HasValue("Creature");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Entities.Character", b =>
                {
                    b.HasBaseType("MasterAdvantage.Shared.Entities.Creature");

                    b.Property<int>("AcrobaticsMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AgilitySave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArcanaMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AthleticsMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwarenessMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Charisma")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CharismaSave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomKnowledge1Mastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomKnowledge1Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomKnowledge2Mastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomKnowledge2Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HistoryMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InfluenceMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InsightMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IntelligenceSave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntimidationMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvestigationMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MedicineMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Might")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MightSave")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NatureMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OccultismMastery")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReligionMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StealthMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurvivalMastery")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrickeryMastery")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Character");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66432fcd-8910-4364-9579-6e9b26417270"),
                            ActionPoints = 4,
                            Conditions = "[]",
                            MD = 0,
                            MDR = 0,
                            MaxHP = 0,
                            MaxMana = 0,
                            MaxStamina = 0,
                            Name = "The Bear Dru",
                            PD = 0,
                            PDR = 0,
                            AcrobaticsMastery = 0,
                            Agility = 0,
                            AgilitySave = false,
                            AnimalMastery = 0,
                            ArcanaMastery = 0,
                            AthleticsMastery = 0,
                            AwarenessMastery = 0,
                            Charisma = 0,
                            CharismaSave = false,
                            CustomKnowledge1Mastery = 0,
                            CustomKnowledge1Name = "",
                            CustomKnowledge2Mastery = 0,
                            CustomKnowledge2Name = "",
                            HistoryMastery = 0,
                            InfluenceMastery = 0,
                            InsightMastery = 0,
                            Intelligence = 0,
                            IntelligenceSave = false,
                            IntimidationMastery = 0,
                            InvestigationMastery = 0,
                            Level = 1,
                            MedicineMastery = 0,
                            Might = 0,
                            MightSave = false,
                            NatureMastery = 0,
                            OccultismMastery = 0,
                            PlayerName = "Nate",
                            ReligionMastery = 0,
                            StealthMastery = 0,
                            SurvivalMastery = 0,
                            TrickeryMastery = 0
                        },
                        new
                        {
                            Id = new Guid("0b655dc7-1f5f-4afe-b384-d8b4298b704e"),
                            ActionPoints = 4,
                            Conditions = "[]",
                            MD = 0,
                            MDR = 0,
                            MaxHP = 0,
                            MaxMana = 0,
                            MaxStamina = 0,
                            Name = "Ishraq",
                            PD = 0,
                            PDR = 0,
                            AcrobaticsMastery = 0,
                            Agility = 0,
                            AgilitySave = false,
                            AnimalMastery = 0,
                            ArcanaMastery = 0,
                            AthleticsMastery = 0,
                            AwarenessMastery = 0,
                            Charisma = 0,
                            CharismaSave = false,
                            CustomKnowledge1Mastery = 0,
                            CustomKnowledge1Name = "",
                            CustomKnowledge2Mastery = 0,
                            CustomKnowledge2Name = "",
                            HistoryMastery = 0,
                            InfluenceMastery = 0,
                            InsightMastery = 0,
                            Intelligence = 0,
                            IntelligenceSave = false,
                            IntimidationMastery = 0,
                            InvestigationMastery = 0,
                            Level = 1,
                            MedicineMastery = 0,
                            Might = 0,
                            MightSave = false,
                            NatureMastery = 0,
                            OccultismMastery = 0,
                            PlayerName = "James",
                            ReligionMastery = 0,
                            StealthMastery = 0,
                            SurvivalMastery = 0,
                            TrickeryMastery = 0
                        },
                        new
                        {
                            Id = new Guid("09fb353d-e506-44ee-a7e4-4cd3a09a13bc"),
                            ActionPoints = 4,
                            Conditions = "[]",
                            MD = 0,
                            MDR = 0,
                            MaxHP = 0,
                            MaxMana = 0,
                            MaxStamina = 0,
                            Name = "Kerf",
                            PD = 0,
                            PDR = 0,
                            AcrobaticsMastery = 0,
                            Agility = 0,
                            AgilitySave = false,
                            AnimalMastery = 0,
                            ArcanaMastery = 0,
                            AthleticsMastery = 0,
                            AwarenessMastery = 0,
                            Charisma = 0,
                            CharismaSave = false,
                            CustomKnowledge1Mastery = 0,
                            CustomKnowledge1Name = "",
                            CustomKnowledge2Mastery = 0,
                            CustomKnowledge2Name = "",
                            HistoryMastery = 0,
                            InfluenceMastery = 0,
                            InsightMastery = 0,
                            Intelligence = 0,
                            IntelligenceSave = false,
                            IntimidationMastery = 0,
                            InvestigationMastery = 0,
                            Level = 1,
                            MedicineMastery = 0,
                            Might = 0,
                            MightSave = false,
                            NatureMastery = 0,
                            OccultismMastery = 0,
                            PlayerName = "Alex",
                            ReligionMastery = 0,
                            StealthMastery = 0,
                            SurvivalMastery = 0,
                            TrickeryMastery = 0
                        },
                        new
                        {
                            Id = new Guid("8333de00-7bf7-4394-850d-d42c794bdd2d"),
                            ActionPoints = 4,
                            Conditions = "[]",
                            MD = 0,
                            MDR = 0,
                            MaxHP = 0,
                            MaxMana = 0,
                            MaxStamina = 0,
                            Name = "Marf",
                            PD = 0,
                            PDR = 0,
                            AcrobaticsMastery = 0,
                            Agility = 0,
                            AgilitySave = false,
                            AnimalMastery = 0,
                            ArcanaMastery = 0,
                            AthleticsMastery = 0,
                            AwarenessMastery = 0,
                            Charisma = 0,
                            CharismaSave = false,
                            CustomKnowledge1Mastery = 0,
                            CustomKnowledge1Name = "",
                            CustomKnowledge2Mastery = 0,
                            CustomKnowledge2Name = "",
                            HistoryMastery = 0,
                            InfluenceMastery = 0,
                            InsightMastery = 0,
                            Intelligence = 0,
                            IntelligenceSave = false,
                            IntimidationMastery = 0,
                            InvestigationMastery = 0,
                            Level = 1,
                            MedicineMastery = 0,
                            Might = 0,
                            MightSave = false,
                            NatureMastery = 0,
                            OccultismMastery = 0,
                            PlayerName = "Spence",
                            ReligionMastery = 0,
                            StealthMastery = 0,
                            SurvivalMastery = 0,
                            TrickeryMastery = 0
                        });
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Components.EncounterItem", b =>
                {
                    b.HasOne("MasterAdvantage.Shared.Entities.Creature", "Creature")
                        .WithMany()
                        .HasForeignKey("CreatureId");

                    b.HasOne("MasterAdvantage.Shared.Components.Encounter", "Encounter")
                        .WithMany("Items")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creature");

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("MasterAdvantage.Shared.Components.Encounter", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
